# Site settings
course_name: Introduction to Cognitive Neuroscience
course_description: "Cognitive Neuroscience is an exciting and rapidly 
evolving eld that bridges the gap between 
neuroscience, psychology, and computational 
modeling. It offers deep insights into how the brain 
enables perception, thought, learning, and behavior. 
This course provides a foundational understanding of 
neural systems, their structure and function, and the 
methods used to study the brain—from cellular and 
molecular mechanisms to large-scale network 
dynamics. Students will explore how the brain encodes 
and processes information, spanning the intricate 
dynamics of neural activity, sensory representations, 
and motor control. The course goes into fundamental 
neural computations, uncovering how biological and 
theoretical models help explain cognition, perception, 
and action. In parallel, we have hands-on workshops, 
including neural data analysis (spikes, LFPs, EEG), fMRI 
interpretation, and cognitive modeling. This year, we 
introduce NeuroAI, to the curriculum where we dive 
into brain-inspired architectures, the synergy between 
deep learning and cognitive science, and how AI can 
help us understand, model, and predict neural and 
cognitive processes."
course_semester: "Spring 2025"

baseurl: "/ICNspring2025"
url: "http://bcolabcourses.github.io/" # the base hostname & protocol for your site

schoolname: "University of Tehran"
schoolurl: "https://bcolab.ut.ac.ir/"
#twitter_username: username 

address: |
    School of Electrical and Computer Engineering
    University of Tehran
    Tehran, Iran

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
